services:
  app:
    image: my-app-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./my-app-frontend-dist/:/app
    container_name: my-app-frontend
  server:
    image: my-app-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/usr/src/app
    container_name: my-app-backend
  nginx:
    image: nginx:1.29.0
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./my-app-frontend-dist:/usr/share/nginx/html:ro
    ports:
      - 8080:80
    container_name: my-app-nginx
    depends_on:
      - app
      - server
volumes:
  my-app-frontend-dist:
