POST http://localhost:3003/api/patients/d2773c6e-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json
Accept: application/json

{
    "date": "2025-06-13",
    "type": "OccupationalHealthcare",
    "specialist": "Dr Bort",
    "employerName": "FSO",
    "diagnosisCodes": [
        "Z74.3",
        "M51.2"
    ],
    "description": "Patient was draining hard!",
    "sickLeave": {
        "startDate": "2025-05-29",
        "endDate": "2025-06-12"
    }
}